insert into clientes values (1, 'Betina Isabelly Stefany Mendes', 'Duque de Caxias', 'RJ');
insert into clientes values (2,'Betania Isabella Stefania Mendes', 'Duque de Caxias', 'RJ');
insert into clientes values (3,'Isabel Stefany Mendes', 'Rio de Janeiro', 'RJ');
insert into clientes values (4,'Stefany Mendes', 'Guapimirim', 'RJ');
insert into clientes values (5,'Rodrigo Mendes', 'Manhumirim', 'MG');
insert into clientes values (6,'Beti Isabel Stelany Mendes', 'Formiga', 'MG');
insert into clientes values (7,'Tina Benevides Silva Moura', 'Duque', 'MG');
insert into clientes values (8,'Estela Moura', 'Caxias', 'MG');
insert into clientes values (9,'Beatriz Ivani Silva', 'Camarim', 'MG');
insert into clientes values (10,'Carla Bianca Silva Torres', 'Americana', 'SP');
insert into clientes values (11,'Luiz Ricardo Jovelino Silva', 'São Paulo', 'SP');
insert into clientes values (12,'Lauro Gusmão Silvano de Moura', 'Santo André', 'SP');
insert into clientes values (13,'Emílio Roberto Mendes', 'Guarulhos', 'SP');
insert into clientes values (14,'Roberto Crispino Stefanio de Moura', 'Divinópolis', 'MG');
insert into clientes values (15,'Ricardo Ismael Rocha', 'Marília', 'SP');
insert into clientes values (16,'Reinaldo Estéfano', 'Santo André', 'SP');
insert into clientes values (17,'Mário Jovelino Braga', 'Bragança', 'SP');
insert into clientes values (18,'Benício Israel de Jesus Mendes', 'Duque de Mauá', 'RS');
insert into clientes values (19,'Jair Marcos Silva', 'Oiapoque', 'SC');
insert into clientes values (20,'Amazonino Mendes', 'Amazonas', 'AM');