insert into produtos values (1, 'Cafeteira Oficial Stefany Mendes', 60);
insert into produtos values (2, 'Boneca Mariana', 32.55);
insert into produtos values (3, 'Livro Aventuras de Isabela e Mendes', 14.98);
insert into produtos values (4, 'Miniatura Hot Weels Monster Machine Series', 10);
insert into produtos values (5, 'Raquete Barbie for Dummies', 98.00);
insert into produtos values (6, 'Bola Topper Oficial', 55);
insert into produtos values (7, 'Tinta Gel Silva Moura', 32.45);
insert into produtos values (8, 'Estrela Pula Pula', 98);
insert into produtos values (9, 'Boneca Ivani Oficial', 54);
insert into produtos values (10,'Caminhão de Bombeiros', 33.45);
insert into produtos values (11,'Lápis de Cor Paulista', 32.00);
insert into produtos values (12,'Hidrocor Santo André', 12.54);
insert into produtos values (13,'Boneca Emília', 11.55);
insert into produtos values (14,'Livro Hobbit', 6.55);
insert into produtos values (15,'Tablet Meu Primeiro Gradiente', 200.65);
insert into produtos values (16,'Tablet Active Sony', 322.14);
insert into produtos values (17,'Boneco Mário Marciano', 98.44);
insert into produtos values (18,'Bola de Tênis Neymar SQN', 41.22);
insert into produtos values (19,'Jira Pião Gasllite',65);
insert into produtos values (20,'Massinha Jira Mendes', 5);